version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wp
    volumes: 
      - dbdata:/var/lib/mysql
#    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wp-network

  wp:
    depends_on: 
      - db
    image: wordpress:5.2.3-fpm
    container_name: wp
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wp
    volumes:
      - wp:/var/www/html
    networks:
      - wp-network

  nginx:
    depends_on:
      - wp
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - wp:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
#      - certbot-etc:/etc/letsencrypt
    networks:
      - wp-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
#      PMA_ARBITRARY: 1 #allows any server
      PMA_HOST: db
      PMA_ABSOLUTE_URI: $PMA_URI
    restart: unless-stopped
    ports:
      - "8001:80"
    networks:
      - wp-network

volumes:
#  certbot-etc:
  wp:
  dbdata:

networks:
  wp-network:
    driver: bridge
